---
output: 
  pdf_document:
    latex_engine: lualatex
    template: svm-latex-cv.tex
    keep_tex: true
geometry: margin=0.75in

title: "CV"
author: Mika Braginsky

email: mikabr@stanford.edu
github: mikabr
web: mikabr.io

mainfont: SourceSerif4Light
mainfontoptions:
  - BoldFont=SourceSerif4SemiBold
  - ItalicFont=SourceSerif4LightItalic
sansfont: SourceSans3
monofont: SourceCodePro
monofontoptions: Scale=0.9
fontsize: 11pt

fontawesome: true
graphics: true
linkcolor: #268bd2
urlcolor: #268bd2
---


# Education

| **Massachusetts Institute of Technology**
|    Ph.D., Cognitive Science (2022)
|    Advisor: Edward Gibson
|    Committee: Edward Gibson, Michael Frank, Timothy O'Donnell, Joshua Tenenbaum, Laura Schulz
|    Thesis: *Language learning at scale: Data-driven and model-motivated analyses of lexical and morphological development*

| **Massachusetts Institute of Technology**
|    B.S., Computer Science and Engineering \& Brain and Cognitive Sciences (2014)


# Research Experience

| **Software Developer** \hfill Sep 2023 -- Present
|    Language and Cognition Lab, Stanford University
|    PI: Michael Frank

| **Postdoctoral Scholar** \hfill Mar 2022 -- Apr 2023
|    Quantitative Sciences Unit, Stanford University
|    PI: Maya Mathur

| **Graduate Student Researcher** \hfill Sep 2016 -- Jan 2022
|    TedLab, MIT (PI: Edward Gibson)
|    Computational Psycholinguistics Lab, MIT (PI: Roger Levy)

| **Research Assistant** \hfill Sep 2014 -- June 2016
|    Language and Cognition Lab, Stanford University
|    PI: Michael Frank

| **Undergraduate Researcher** \hfill Sep 2013 -- Aug 2014
|    Computational Cognitive Science Group, MIT
|    PI: Joshua Tenenbaum

<!-- | **Research and Development Intern** \hfill June 2013 -- Aug 2013 -->
<!-- |    Research and Development Team, Basis Technology -->


# Awards and Fellowships

- Cognitive Development Society Book Award for *Variability and Consistency in Early Language Learning: The Wordbank Project* (2024)
- Walle Nauta Award for Continuing Dedication to Teaching by a Graduate Student (2020, 2021, 2022)
- Angus MacDonald Award for Excellence in Undergraduate Teaching (2019)
- Henry E. Singleton Fellowship, MIT (2017--2018)
- Society for Language Development Student Award (2016)
- **National Science Foundation Graduate Research Fellowship** (2016--2021)


# Books

- Frank, M. C., **Braginsky, M.**, Cachia, J., Coles, N., Hardwicke, T., Hawkins, R., Mathur, M., and Williams, R. (in press). Experimentology: An Open Science Approach to Experimental Psychology Methods. MIT Press. `experimentology.io`

- Frank, M. C., **Braginsky, M.**, Marchman, V. A., and Yurovsky, D. (2021). Variability and Consistency in Early Language Learning: The Wordbank Project. MIT Press. `wordbank-book.stanford.edu`


# Book Chapters

- Mahowald, K., Dautriche, I., **Braginsky, M.**, and Gibson, E. (2022). Efficient communication and the organization of the lexicon. In *Oxford Handbook of the Mental Lexicon*. Oxford University Press.


# Journal Articles

- Frank, M. C., Marchman, V. A., Bergey, C. A., Boyce, V., **Braginsky, M.**, Kachergis, G., ..., Zettersten, M. (under review). Continuous developmental changes in word recognition support language learning across early childhood. Pre-print: https://doi.org/10.31234/osf.io/dtv2f_v1.

- Frank, M. C., Baumgartner, H. A., **Braginsky, M.**, Kachergis, G., Lightbody, A. A., ..., Cubillo, A., Dodge, K. A. (under revision). Learning Variability Network Exchange (LEVANTE): A global framework for measuring children's learning variability through collaborative data sharing. Pre-print: https://doi.org/10.31234/osf.io/namx2.

- Domingue, B., **Braginsky, M.**, Caffrey-Maffei, L., Gilbert, J. B., Kanopka, K., Kapoor, R., ..., Frank, M. C. (under revision). Solving the problem of data in psychometrics: An introduction to the Item Response Warehouse (IRW). Pre-print: https://doi.org/10.31234/osf.io/7bd54.

<!-- - Yuen, F, Kline, M., Zettersten, M, Kosie, J., **Braginsky, M**, Frank, M. C. (in prep). ShinyValidator: A user-friendly Shiny application for validating data standards. -->

<!-- - Pimentel, T., Ryskina, M., Ambridge,	B., Anastasopoulos, A., Anderson, N., Arora, A., Bonami, O., **Braginsky, M.**, et al (under review). Sint vs Sinded: Do Machines Inflect Nonce Words Similar to Humans? ACL Rolling Review. -->

- Voşki, A., **Braginsky, M.**, Zhang, A., Bertoldo, J., Egan, S., Levig, L.A., Mueller Ihrig, M., & Mathur, M. B. (2025). Effect of a default portion-size reduction on meat consumption and diner satisfaction: Controlled experiments in Stanford University dining halls. BMC Public Health.

- Poliak, M., Ryskin, R., **Braginsky, M.**, Gibson, E. (2024). It's not what you say but how you say it: Evidence from Russian shows robust effects of the structural prior on noisy channel inferences. Journal of Experimental Psychology: Learning, Memory, and Cognition.

- Zettersten, M., Yurovsky, D., Xu, T., Uner, S., Tsui, A., ... **Braginsky, M.**, ... Frank, M. C. (2023). Peekbank: An open, large-scale repository for developmental eye-tracking data of children’s word recognition. Behavior Research Methods.

- DeMayo, B., Kellier, D., **Braginsky, M.**, Bergmann, C., Hendriks, C., Rowland, C. F., Frank, M. C., & Marchman, V. (2021). Web-CDI: A system for online administration of the MacArthur-Bates Communicative Development Inventories. Language Development Research.

- **Braginsky, M.**, Yurovsky, D., Marchman, V. A., and Frank, M. C. (2019). Consistency and variability in children's word learning across languages. OpenMind: Discoveries in Cognitive Science.

- Sanchez, A., Meylan, S. C., **Braginsky, M.**, MacDonald, K. E., Yurovsky, D., and Frank, M. C. (2019). childes-db: a flexible and reproducible interface to the Child Language Data Exchange System. Behavioral Research Methods.

- Bergmann, C., Tsuji, S., Piccinini, P., Lewis, M., **Braginsky, M.**, Frank, M. C., and Cristia, A. (2018). Promoting replicability in developmental research through meta-analyses: Insights from language acquisition research. Child Development.

- Frank, M. C., **Braginsky, M.**, Yurovsky, D., and Marchman, V. A. (2016). Wordbank: An open repository for developmental vocabulary data. Journal of Child Language.


# Peer-Reviewed Conference Proceedings

- Tan, A., Loukatou, G., **Braginsky, M.**, Mankewitz, J., and Frank, M. C. (2024). Predicting ages of acquisition for children's early vocabulary across 27 languages and dialects. In *Proceedings of the 46th Annual Meeting of the Cognitive Science Society*.

- Ambridge,	B.,	Anastasopoulos,	A.,	Anderson,	N.,	Arora,	A.,	Bonami,	O.,	**Braginsky,	M.**, et al (2021). A pipeline for generating plausible wug words in many languages. In *Proceedings of the 18th SIGMORPHON Workshop on Computational Research in Phonetics, Phonology, and	Morphology*.

- Zettersten, M., Bergey, C., Bhatt, N., Boyce, V., **Braginsky, M.**, Carstensen, A., ... & Frank, M. C. (2021). Peekbank: Exploring children's word recognition through an open, large-scale repository for developmental eye-tracking data. In *Proceedings of the 43rd Annual Meeting of the Cognitive Science Society*.

- Tenenbaum, A., **Braginsky, M.**, and Levy, R. (2020). Integrating semantics into developmental models of morphology learning. In *Proceedings of the 42nd Annual Meeting of the Cognitive Science Society*.

- **Braginsky, M.**, Yurovsky, D., Marchman, V. A., and Frank, M. C. (2016). From *uh-oh* to *tomorrow*: Predicting age of acquisition for early words across languages. In *Proceedings of the 38th Annual Meeting of the Cognitive Science Society*.

- **Braginsky, M.**, Yurovsky, D., Marchman, V. A., and Frank, M. C. (2015). Developmental changes in the relationship between grammar and the lexicon. In *Proceedings of the 37th Annual Meeting of the Cognitive Science Society*.


# Conference Presentations

- **Braginsky, M.**, and Frank, M. C. (Aug 2024). Datapages for interactive data sharing using Quarto. Talk presented at posit::conf 2024. [youtube.com/watch?v=1gUl-vWqScc](https://www.youtube.com/watch?v=1gUl-vWqScc).

- **Braginsky, M.**, and Mathur, M. (Mar 2023). Tools for accounting for within-study and across-study biases in meta-analysis. Talk presented at Evidence Synthesis and Meta-Analysis in R Conference 2023. [youtube.com/watch?v=O6RSRLDOmmc](https://www.youtube.com/watch?v=O6RSRLDOmmc).

- Loukatou, G., Tan, A., **Braginsky, M.**, Mankewitz, J. and Frank, M. C. (November 2022). Typological variation in predicting early word learning across languages. Poster presented by Alvin Tan at the 47th Annual Boston University Conference on Language Development.

- Zettersten, M., Bergey, C., Bhatt, N., Boyce, V., **Braginsky, M.**, Carstensen, A., ... & Frank, M. C. (October 2022). Peekbank: Exploring children's word recognition through an open, large-scale repository for developmental eye-tracking data. Talk presented by Martin Zettersten at the 2022 Big Team Science Conference.

- Zettersten, M., Saleh, A, Bhatt, N., Yurovsky, D., Xu, T. L., ..., **Braginsky, M.**, ..., and Frank, M. C. (November 2021). Increases in speed and accuracy of children's online word recognition measured via a large-scale, open database of developmental eye-tracking data. Talk presented by Martin Zettersten at the 46th Annual Boston University Conference on Language Development.

- Watt, M., **Braginsky, M.**, and O'Donnell, T. (July 2021). Processing differences among irregular inflection classes. Poster presented by Maya Watt at the 43rd Annual Meeting of the Cognitive Science Society.

- Zettersten, M., Bergey, C., Bhatt, N., Boyce, V., **Braginsky, M.**, Carstensen, A., ... & Frank, M. C. (July 2021). Peekbank: Exploring children's word recognition through an open, large-scale repository for developmental eye-tracking data. Poster presented by Martin Zettersten at the 43rd Annual Meeting of the Cognitive Science Society.

- **Braginsky, M.**, Marchman, V. A., and Frank, M. C. (July 2020). Characterizing the relationship between lexical and morphological development. Poster presented at the 42nd Annual Meeting of the Cognitive Science Society.

- Tenenbaum, A., **Braginsky, M.**, and Levy, R. (July 2020). Integrating semantics into developmental models of morphology learning. Poster presented by Abigail Tenenbaum at the 42nd Annual Meeting of the Cognitive Science Society.

- **Braginsky, M.**, Marchman, V. A., and Frank, M. C. (July 2020). Characterizing the relationship between lexical and morphological development. Talk presented at the XXII Biennial International Congress of Infant Studies.

- Meylan, S, **Braginsky, M.**, deMayo, B., Sanchez, A., Schonberg, C., Srinivasan, M., Vlach, H., Lupyan, G., Griffiths, T., Frank, M. C. (November 2019). Wordful: Tracking early productive vocabulary growth with smartphones. Talk presented by Stephan Meylan at the 44th Annual Boston University Conference on Language Development.

- **Braginsky, M.**, Marchman, V. A., and Frank, M. C. (March 2019). Demographic effects on the composition of children's early vocabulary. Talk presented at the 2019 Society for Research in Child Development Biennial Meeting.

- **Braginsky, M.**, Levy, R., and O'Donnell, T. (July 2018). Evaluating models of productivity in language acquisition. Poster presented at the 40th Annual Meeting of the Cognitive Science Society.

- Tsuji, S., Bergmann, C., Lewis, M., **Braginsky, M.**, Piccinini, P., Frank, M. C., and Cristia, A. (August 2017). MetaLab: A repository for meta-analyses on language development, and more. Talk presented by Sho Tsuji at Interspeech 2017.

- **Braginsky, M.**, Yurovsky, D., Meylan, S., Marchman, V. A., and Frank, M. C. (April 2017). Building quantitative theories of early language using large-scale parent report data. Talk presented at the 2017 Society for Research in Child Development Biennial Meeting.

- **Braginsky, M.**, Yurovsky, D., Meylan, S., Marchman, V. A., and Frank, M. C. (November 2016). Gender differences in lexical input and acquisition. Talk presented at the 41th Annual Boston University Conference on Language Development.

- **Braginsky, M.**, Yurovsky, D., Marchman, V. A., and Frank, M. C. (August 2016). From *uh-oh* to *tomorrow*: Predicting age of acquisition for early words across languages. Talk presented at the 38th Annual Meeting of the Cognitive Science Society.

- **Braginsky, M.**, Yurovsky, D., Marchman, V. A., and Frank, M. C. (May 2016). Predicting age of acquisition for early words across languages. Talk presented at the XX Biennial International Congress of Infant Studies.

- **Braginsky, M.** (January 2016). Using Shiny for exploration of Wordbank. RStudio Shiny Developer Conference.

- Tsuji, S., Bergmann, C., Cristia, A., Lewis, M., **Braginsky, M.**, and Frank, M. C. (January 2016). MetaLab: Power analysis and experimental planning in developmental research made easy. Poster presented by Sho Tsuji at the 2015 Budapest CEU Conference on Cognitive Development.

- **Braginsky, M.**, Yurovsky, D., Marchman, V. A., and Frank, M. C. (December 2015). Predicting age of acquisition for early words across languages. Talk presented at the Studying Language Learning Workshop.

- **Braginsky, M.**, Yurovsky, D., Marchman, V. A., and Frank, M. C. (November 2015). Developmental trajectories of vocabulary composition across languages. Poster presented at the 40th Annual Boston University Conference on Language Development.

- Lewis, M., **Braginsky, M.**, Bergmann, C., Tsuji, S., Cristia, A., and Frank, M. C. (November 2015). MetaLab: A tool for power analysis and experimental planning in developmental research. Talk presented by Molly Lewis at the 40th Annual Boston University Conference on Language Development.

- **Braginsky, M.**, Yurovsky, D., Marchman, V. A., and Frank, M. C. (July 2015). Developmental changes in the relationship between grammar and the lexicon. Poster presented at the 37th Annual Meeting of the Cognitive Science Society.

- Frank, M. C., Yurovsky, D., Schneider, R., **Braginsky, M.**, and Marchman, V. A. (March 2015). Studying children's vocabulary development at scale. Talk presented by Michael Frank at the 2015 Society for Research in Child Development Biennial Meeting.

- Frank, M. C., Yurovsky, D., Krishna, R., **Braginsky, M.**, and Marchman, V. A. (November 2014). Wordbank: An open repository for developmental vocabulary data. Poster presented by Michael Frank at the 39th Annual Boston University Conference on Language Development. Boston, MA.


# Departmental Presentations

- **Braginsky, M.**. (October 2022). Tools for fitting generalized linear mixed-effects models in Julia from R. Research Methods Seminar, Quantitative Sciences Unit, Stanford University.

- **Braginsky, M.**, Marchman, V. A., and Frank, M. C. (November 2019). Characterizing the relationship between lexical and morphological development. Emerging Scholars of Psychological Science, Princeton University.

- **Braginsky, M.** (October 2018). Understanding productivity inferences in children and models. CogLunch, Department of Brain and Cognitive Sciences, MIT.

- **Braginsky, M.**, Levy, R., and O'Donnell, T. (October 2017). Bayesian models of productivity in acquisition. CogLunch, Department of Brain and Cognitive Sciences, MIT.


# Teaching

| **Teaching Assistant** \hfill Spring 2021, Spring 2020, Spring 2019, Spring 2018
|     Laboratory in Psycholinguistics, MIT
|     Instructor: Edward Gibson

| **Workshop Instructor** \hfill July 2019
|     Large-scale data tools in child language acquisition
|     Linguistic Society of America 2019 Linguistic Institute
|     Co-instructor: Michael Frank

| **Advanced Learning Assistant** \hfill Fall 2011
|     Introduction to Electrical Engineering and Computer Science I


# Service

- Ad-hoc reviewer for Journal of Child Language, Language Development Research, Cognitive Science Society
- Co-organizer of weekly CogLunch talk series in MIT BCS department \hfill Sep 2017 -- May 2018


# Software

| __`metabias`__ (co-creator and former maintainer) \hfill `metabias.io`
|    R packages for bias-corrections for meta-analysis (`multibiasmeta`, `phacking`, `PublicationBias`)
|    Interactive visualizations and tools

| __Wordbank__ (co-creator and maintainer) \hfill `wordbank.stanford.edu`
|    Open repository of parent-report data on children's early language learning <!--\hfill `github.com/langcog/wordbank`-->
|    Interactive visualizations and tools <!--\hfill `github.com/langcog/wordbank-shiny`-->
|    R package for data access and manipulation (`wordbankr`) <!--\hfill `github.com/langcog/wordbankr`-->

| __childes-db__ (co-creator and maintainer) \hfill `childes-db.stanford.edu`
|    Flexible and reproducible interface to CHILDES, a corpus of child language transcripts <!--\hfill `github.com/langcog/childes-db`-->
|    R package for data access (`childesr`) <!--\hfill `github.com/langcog/childesr`-->

| __Peekbank__ (co-creator and maintainer) \hfill `peekbank.stanford.edu`
|    Flexible and reproducible interface to developmental eyetracking datasets <!--\hfill `github.com/langcog/peekbank`-->
|    R package for data access (`peekbankr`) <!--\hfill `github.com/langcog/peekbankr`-->

| __Wordful__ (co-creator and former maintainer) \hfill `wordfulapp.com`
|    Smartphone app for tracking early vocabulary growth

| __MetaLab__ (co-creator and former maintainer) \hfill `metalab.stanford.edu`
|    Interactive tools for community-augmented meta-analysis in cognitive development research

| __`rwebppl`__ (co-creator and former maintainer) \hfill `github.com/mhtess/rwebppl`
|    R interface to the WebPPL probabilistic programming language

| __`jglmm`__ (creator and maintainer) \hfill `github.com/mikabr/jglmm`
|    R package for fitting generalized linear fixed effects models in Julia

| __`ggpirate`__ (creator and maintainer) \hfill `github.com/mikabr/ggpirate`
|    R package for making plots of data with categorical independent variables

| __`tidyboot`__ (co-creator and maintainer) \hfill `github.com/langcog/tidyboot`
|    R package for doing tidyverse-compatible bootstrapping

\centering
\vspace{2em}
_Last updated: `r Sys.Date()`_
